import { ITaskItem } from '../task/Task.model';

export const TASKS: ITaskItem[] = [
    { id: '1', title: 'Задача 1', priorityColor: '#FF0000' },
    { id: '2', title: 'Задача 2', priorityColor: '#0000FF' },
    { id: '3', title: 'Задача 3', priorityColor: '#00FF00' },
    { id: '4', title: 'Задача 4', priorityColor: '#FFFF00' },
    { id: '5', title: 'Задача 5', priorityColor: '#800080' },
    { id: '6', title: 'Задача 6', priorityColor: '#FFA500' },
    { id: '7', title: 'Задача 7', priorityColor: '#FFC0CB' },
    { id: '8', title: 'Задача 8', priorityColor: '#FF0000' },
    { id: '9', title: 'Задача 9', priorityColor: '#0000FF' },
    { id: '10', title: 'Задача 10', priorityColor: '#00FF00' },
    { id: '11', title: 'Задача 11', priorityColor: '#FFFF00' },
    { id: '12', title: 'Задача 12', priorityColor: '#800080' },
    { id: '13', title: 'Задача 13', priorityColor: '#FFA500' },
    { id: '14', title: 'Задача 14', priorityColor: '#FFC0CB' },
    { id: '15', title: 'Задача 15', priorityColor: '#FF0000' },
    { id: '16', title: 'Задача 16', priorityColor: '#0000FF' },
    { id: '17', title: 'Задача 17', priorityColor: '#00FF00' },
    { id: '18', title: 'Задача 18', priorityColor: '#FFFF00' },
    { id: '19', title: 'Задача 19', priorityColor: '#800080' },
    { id: '20', title: 'Задача 20', priorityColor: '#FFA500' },
    { id: '21', title: 'Задача 21', priorityColor: '#FFC0CB' },
    { id: '22', title: 'Задача 22', priorityColor: '#FF0000' },
    { id: '23', title: 'Задача 23', priorityColor: '#0000FF' },
    { id: '24', title: 'Задача 24', priorityColor: '#00FF00' },
    { id: '25', title: 'Задача 25', priorityColor: '' },
];
